routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PostcodeController@index');
Route::post('/search', 'PostcodeController@search')->name('postcodes.search');
Route::resource('postcodes', 'PostcodeController', ['only' => ['show']]);

app/Models/Postcode.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Postcode extends Model
{
	public $timestamps = false;
	protected $fillable = [
		'postcode', 'country', 'region'
	];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostcodeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Postcode;
use App\Http\Requests\PostcodeRequest;

class PostcodeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $postcodes = Postcode::all();
        return view('postcode.index', compact('postcodes'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Postcode  $postcode
     * @return \Illuminate\Http\Response
     */
    public function show(Postcode $postcode)
    {
        return view('postcode.show', compact('postcode'));
    }

    /**
     * Search postcode by name
     *
     * @param  PostcodeRequest  $request
     * @return mixed \Illuminate\Http\Response|Illuminate\Support\Facades\Redirect
     */
    public function search(PostcodeRequest $request)
    {
        // Illuminate\Support\ServiceProvider
        return app('postcode')->search($request->postcode);
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/postcode/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Postcodes</div>
                    <div class="card-body">
                        {{ Form::open(['route' => 'postcodes.search', 'method' => 'POST']) }}
                            <div class="form-group">
                                {{ Form::label('postcode', 'Postcode') }}
                                {{ Form::text('postcode', null, ['class' => 'form-control', 'placeholder' => 'Enter postcode', 'required']) }}

                                @if ($errors->has('postcode'))
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $errors->first('postcode') }}</strong>
                                    </span>
                                @endif

                                @if (session()->has('api_error'))
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ session('api_error') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group">
                                {{ Form::submit('Find', ['class' => 'btn btn-primary']) }}
                            </div>
                        {{ Form::close() }}
                        <hr>
                        @foreach($postcodes as $postcode)
                            <a href="{{ route('postcodes.show', $postcode) }}">{{ $postcode->postcode }}</a>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/postcode/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Postcode - {{ $postcode->postcode }}</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">{{ $postcode->postcode }}</div>
                            <div class="col-md-4">{{ $postcode->country }}</div>
                            <div class="col-md-4">{{ $postcode->region }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection